//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSops.CommandLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotSops.CommandLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt secrets into dotnet user secrets.
        /// </summary>
        internal static string DecryptCommandDescription {
            get {
                return ResourceManager.GetString("DecryptCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of the encrypted secrets.
        /// </summary>
        internal static string DecryptCommandFileOptionDescription {
            get {
                return ResourceManager.GetString("DecryptCommandFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to project. Defaults to searching the current directory.
        /// </summary>
        internal static string DecryptCommandProjectOptionDescription {
            get {
                return ResourceManager.GetString("DecryptCommandProjectOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user secret ID to use..
        /// </summary>
        internal static string DecryptCommandSecretsIdOptionDescription {
            get {
                return ResourceManager.GetString("DecryptCommandSecretsIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SOPS from https://github.com/getsops/sops.
        /// </summary>
        internal static string DownloadSopsCommandDescription {
            get {
                return ResourceManager.GetString("DownloadSopsCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading SOPS.
        /// </summary>
        internal static string DownloadSopsLoader {
            get {
                return ResourceManager.GetString("DownloadSopsLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt existing dotnet user secrets.
        /// </summary>
        internal static string EncryptCommandDescription {
            get {
                return ResourceManager.GetString("EncryptCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of the encrypted secrets.
        /// </summary>
        internal static string EncryptCommandFileOptionDescription {
            get {
                return ResourceManager.GetString("EncryptCommandFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to project. Defaults to searching the current directory.
        /// </summary>
        internal static string EncryptCommandProjectOptionDescription {
            get {
                return ResourceManager.GetString("EncryptCommandProjectOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user secret ID to use..
        /// </summary>
        internal static string EncryptCommandSecretsIdOptionDescription {
            get {
                return ResourceManager.GetString("EncryptCommandSecretsIdOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]File does not exist.[/]
        ///
        ///[yellow]Path: {0}[/].
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .sops.yaml configuration file.
        ///
        ///Documentation on how to create encryptions keys:
        ///Azure Key Vault - https://learn.microsoft.com/en-us/azure/key-vault
        ///GCP KMS - https://cloud.google.com/security-key-management
        ///AWS KMS - https://aws.amazon.com/kms
        ///Hashicorp Vault - https://www.vaultproject.io
        ///age - https://github.com/FiloSottile/age
        ///PGP - https://www.openpgp.org.
        /// </summary>
        internal static string InitializeCommandDescription {
            get {
                return ResourceManager.GetString("InitializeCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Operating system is not supported.[/].
        /// </summary>
        internal static string OperatingSystemNotSupported {
            get {
                return ResourceManager.GetString("OperatingSystemNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store and share encrypted secrets, created using user-secrets tool.
        ///Secrets are encrypted and decrypted using SOPS.
        ///Encrypted secrets can shared with other team members than can decrypt it, if they have access.
        ///
        ///Encryption types is configured using .sops.yaml file. Run &quot;dotnet sops init&quot; for help wizard to create .sops.yaml.
        ///
        ///Warning: When secrets are decrypted they are stored in plain, unencrypted text, that can be loaded by user-secrets tool.
        ///Recomendation: Only store development secrets that canno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose logging output.
        /// </summary>
        internal static string RootDotSopsCommandVerboseOptionDescription {
            get {
                return ResourceManager.GetString("RootDotSopsCommandVerboseOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Failed to download SOPS.[/]
        ///
        ///[yellow]HTTP status code: {0}[/]
        ///[yellow]URL: {1}[/].
        /// </summary>
        internal static string SopsDownloadHttpFailed {
            get {
                return ResourceManager.GetString("SopsDownloadHttpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]SHA512 of SOPS executable did not match.[/]
        ///
        ///[yellow]Expected: {0}[/]
        ///[yellow]Actual:   {1}[/].
        /// </summary>
        internal static string SopsDownloadSha512Failed {
            get {
                return ResourceManager.GetString("SopsDownloadSha512Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]SOPS executable is missing from path environment.[/]
        ///
        ///You can download it by executing the following command:
        ///[yellow]dotnet sops download-sops[/].
        /// </summary>
        internal static string SopsIsMissing {
            get {
                return ResourceManager.GetString("SopsIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]Failed to run sops.[/].
        /// </summary>
        internal static string SopsRunFailed {
            get {
                return ResourceManager.GetString("SopsRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]SOPS failed with error.[/]
        ///
        ///{0}.
        /// </summary>
        internal static string SopsRunFailedWithError {
            get {
                return ResourceManager.GetString("SopsRunFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [red]User secrets file does not exist.[/]
        ///
        ///[yellow]Path: {0}[/].
        /// </summary>
        internal static string UserSecretsFileDoesNotExist {
            get {
                return ResourceManager.GetString("UserSecretsFileDoesNotExist", resourceCulture);
            }
        }
    }
}
